/**
 * Created by boiko on 10/30/2016.
 */
import { Component } from '@angular/core';

@Component({
	           selector: 'blog-posts',
	           template: `
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
<div>blog postz</div>
`
           })
export class PostsPageComponent {}